// Publishes the built cabinet into the folder GitHub Pages actually serves.
//
// The portfolio has no CI — Pages serves committed files as-is — so the
// playable page has to be prebuilt and live at the cabinet root, next to its
// siblings (InterpretiveNetworking/interpretive-networking.html). Vite still
// builds into dist/ (scratch, gitignored); this copies the result up as
// itops.html + assets/.

import { cpSync, rmSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const dist = join(root, 'dist')

if (!existsSync(join(dist, 'index.html'))) {
  throw new Error('No dist/index.html — run `vite build` before releasing.')
}

// Wipe first: asset filenames are content-hashed, so stale bundles would
// otherwise pile up in the committed folder forever.
rmSync(join(root, 'assets'), { recursive: true, force: true })

cpSync(join(dist, 'assets'), join(root, 'assets'), { recursive: true })

// dist/index.html inherits source index.html's "this is the dev entry, not
// the deployed page" comment (Vite preserves HTML comments verbatim) — swap
// it for an itops.html-appropriate one instead of shipping a comment that
// contradicts the file it's sitting in.
const DEV_ENTRY_COMMENT = '<!-- Vite dev-server entry (npm run dev). Not the deployed page — that\'s itops.html, generated from this via `npm run build`. -->'
const RELEASED_COMMENT = '<!-- Generated by scripts/release.mjs from dist/index.html. Do not hand-edit — edit index.html / src/ and re-run `npm run build`. -->'
const built = readFileSync(join(dist, 'index.html'), 'utf8')
writeFileSync(join(root, 'itops.html'), built.replace(DEV_ENTRY_COMMENT, RELEASED_COMMENT))

console.log('Released: itops.html + assets/')
